import { useState } from "react";
import { LANGUAGE_TO_APPLICATION_EXAMPLES } from "../lib/language-to-application";

export default function FromLanguageToApplication({ language }) {
  const [selectedId, setSelectedId] = useState(null);
  const [revealed, setRevealed] = useState(0);
  const ar = language === "ar"; const locale = ar ? "ar" : "en";
  const selected = LANGUAGE_TO_APPLICATION_EXAMPLES.find((item) => item.id === selectedId);
  const labels = ar ? ["الهدف", "المشكلة", "المعلومات", "القدرات", "المسار", "المراحل", "دور الخوارزمية", "التقييم", "تحليل الأخطاء", "المساهمة والحد"] : ["Goal", "Problem", "Information", "Capabilities", "Research path", "Computational stages", "Algorithm/model role", "Evaluation", "Error analysis", "Contribution and boundary"];
  const values = selected ? [selected.goal[locale], selected.problem[locale], selected.information[locale].join(" · "), selected.capabilities[locale].join(" + "), selected.path[locale], selected.stages[locale].join(" → "), selected.algorithm[locale], selected.evaluation[locale], selected.errors[locale], `${selected.contribution[locale]} ${selected.limitation[locale]}`] : [];
  return <section data-testid="from-language-to-application" dir={ar ? "rtl" : "ltr"} aria-labelledby="language-to-application-title" style={{ marginBottom: "32px", padding: "28px", border: "1px solid rgba(73,67,137,.13)", borderRadius: "24px", background: "linear-gradient(135deg,#fff,#f6f4ff)" }}>
    <p style={{ margin: "0 0 8px", color: "#6258f5", fontWeight: 700, fontSize: "12px", letterSpacing: ".08em" }}>{ar ? "استكشاف تفاعلي" : "INTERACTIVE EXPLORATION"}</p><h2 id="language-to-application-title" style={{ margin: 0 }}>{ar ? "من اللغة إلى التطبيق" : "From Language to Application"}</h2><p style={{ color: "#706c88", lineHeight: 1.65 }}>{ar ? "اختر مثالًا ثم اكشف العلاقات بالتدريج. التطبيق ليس خوارزمية، والمسار البحثي يقدّم مساهمة محددة لا منتجًا كاملًا." : "Choose an example, then reveal its relationships progressively. An application is not an algorithm, and a research path contributes a bounded component rather than a complete product."}</p>
    <div role="group" aria-label={ar ? "اختر مثالًا" : "Choose an example"} style={{ display: "flex", flexWrap: "wrap", gap: "8px" }}>{LANGUAGE_TO_APPLICATION_EXAMPLES.map((item) => <button type="button" key={item.id} aria-pressed={selectedId === item.id} onClick={() => { setSelectedId(item.id); setRevealed(1); }} style={{ cursor: "pointer", padding: "9px 12px", borderRadius: "10px", border: selectedId === item.id ? "2px solid #5148d9" : "1px solid #bdb8e9", background: selectedId === item.id ? "#ece9ff" : "#fff", color: "#312c54", fontWeight: 600 }}>{item.title[locale]}</button>)}</div>
    {selected && <div style={{ marginTop: "18px" }}><p role="status" style={{ margin: "0 0 10px", color: "#5148d9", fontWeight: 600 }}>{ar ? "اكشف العلاقة التالية لتبني المسار." : "Reveal the next relationship to construct the path."}</p><ol style={{ margin: 0, paddingInlineStart: "22px" }}>{labels.slice(0, revealed).map((label, index) => <li key={label} style={{ margin: "10px 0", lineHeight: 1.55 }}><strong>{label}:</strong> {values[index]}</li>)}</ol>{revealed < labels.length && <button type="button" onClick={() => setRevealed((value) => value + 1)} style={{ cursor: "pointer", marginTop: "10px", padding: "9px 12px", border: 0, borderRadius: "10px", background: "#6258f5", color: "#fff", fontWeight: 700 }}>{ar ? "اكشف الخطوة التالية" : "Reveal next step"}</button>}</div>}
  </section>;
}
