import { ARABIC_CHALLENGE_PROJECTS } from "./arabic-challenges.js";
import { APPLIED_NEW_PROJECTS, APPLIED_PROJECT_BY_PROJECT_ID } from "./applied-projects.js";
import { SOCIAL_IMPACT_PROJECTS } from "./social-impact-projects.js";

const bi = (en, ar) => ({ en, ar });

export const PATH_GUIDANCE = {
  "corpus-linguistics": { name: bi("Corpus Linguistics", "لسانيات المدونات"), problem: bi("Recurring forms and usage patterns across text collections.", "الأنماط المتكررة واستعمال اللغة في مجموعات النصوص."), questions: bi("Which words, contexts, and sequences distinguish a corpus?", "ما الكلمات والسياقات والمتتاليات التي تميز المدونة؟"), data: bi("Documented text collections with source metadata.", "مجموعات نصية موثقة مع بيانات وصفية للمصدر."), tools: ["Corpus Research", "Frequency", "Concordance / Contexts", "N-grams"], annotation: bi("Optional for description; needed when building a human reference.", "اختياري للوصف، ومطلوب عند بناء مرجع بشري."), outputs: bi("A corpus, pattern evidence, a paper, or a browsing prototype.", "مدونة وأدلة أنماط وورقة بحثية أو نموذج للتصفح."), evaluation: bi("Coverage, metadata completeness, duplicate review, and reproducibility.", "التغطية واكتمال البيانات الوصفية ومراجعة التكرار وقابلية إعادة الإنتاج."), beginner: bi("Understand sampling, corpus boundaries, metadata, and why frequency is not importance.", "افهم العينة وحدود المدونة وبياناتها الوصفية وأن التكرار لا يساوي الأهمية.") },
  "morphology-syntax": { name: bi("Morphology & Syntax", "الصرف والنحو"), problem: bi("Word forms, grammatical categories, ambiguity, and sentence structure.", "صيغ الكلمات والفئات النحوية والغموض والبنية التركيبية."), questions: bi("How do forms and grammatical functions vary by context?", "كيف تختلف الصيغ والوظائف النحوية باختلاف السياق؟"), data: bi("Arabic words or sentences with sufficient context.", "كلمات أو جمل عربية ذات سياق كافٍ."), tools: ["POS", "Morphology & Syntax Research Preview"], annotation: bi("Recommended for ambiguity studies and formal evaluation.", "يوصى به لدراسات الغموض والتقييم المنهجي."), outputs: bi("Reviewed analyses, an ambiguity taxonomy, or an annotated sample.", "تحليلات مراجعة أو تصنيف للغموض أو عينة مرمزة."), evaluation: bi("Human-reference agreement and qualitative error analysis.", "الاتفاق مع المرجع البشري والتحليل النوعي للأخطاء."), beginner: bi("Understand tokens, lemmas, features, POS, and the role of context.", "افهم الوحدات والصيغ المعجمية والسمات وأقسام الكلام ودور السياق.") },
  semantics: { name: bi("Semantics", "الدلالة"), problem: bi("Similarity, topics, and meaning-based groups.", "التشابه والموضوعات والمجموعات القائمة على المعنى."), questions: bi("Which texts express related meanings?", "ما النصوص التي تعبر عن معانٍ مترابطة؟"), data: bi("Comparable Arabic texts and a defined semantic unit.", "نصوص عربية قابلة للمقارنة ووحدة دلالية محددة."), tools: ["Semantics Research Preview"], annotation: bi("Recommended for validating similarity, topics, and groups.", "يوصى به للتحقق من التشابه والموضوعات والمجموعات."), outputs: bi("Reviewed groups, topic labels, or a benchmark sample.", "مجموعات مراجعة وتسميات موضوعية أو عينة معيارية."), evaluation: bi("Human judgments, agreement, and disputed-case analysis.", "الأحكام البشرية والاتفاق وتحليل الحالات المختلف عليها."), beginner: bi("Define what similarity means for the study before comparing outputs.", "حدد معنى التشابه في الدراسة قبل مقارنة المخرجات.") },
  "discourse-pragmatics": { name: bi("Discourse & Pragmatics", "الخطاب والتداولية"), problem: bi("Stance, discourse relations, speech acts, implication, and context.", "الموقف والعلاقات الخطابية والأفعال الكلامية والاستلزام والسياق."), questions: bi("How does language position speakers and construct contextual meaning?", "كيف تتموضع الأصوات ويُبنى المعنى في السياق؟"), data: bi("Complete passages with speaker, genre, or situation metadata when available.", "مقاطع كاملة مع بيانات المتحدث أو النوع أو الموقف عند توفرها."), tools: ["Discourse Analysis", "Pragmatics"], annotation: bi("Usually needed; independent annotators strengthen the reference.", "مطلوب غالبًا، ويقوي المرمزون المستقلون المرجع."), outputs: bi("A human reference, annotation study, paper, or reviewed prototype.", "مرجع بشري أو دراسة ترميز أو ورقة أو نموذج مراجع."), evaluation: bi("Annotator agreement, reference comparison, and evidence review.", "اتفاق المرمزين والمقارنة بالمرجع ومراجعة الأدلة."), beginner: bi("Define the phenomenon, annotation unit, examples, and boundary rules.", "حدد الظاهرة ووحدة الترميز والأمثلة وقواعد الحالات الحدية.") },
  "text-classification": { name: bi("Text Classification", "تصنيف النصوص"), problem: bi("Assign predefined labels and evaluate predictions against human labels.", "إسناد فئات محددة وتقييم التنبؤات مقابل التصنيف البشري."), questions: bi("Can text features distinguish the research categories?", "هل تميز خصائص النص بين فئات البحث؟"), data: bi("Labeled text with text and human-reference columns.", "نصوص مصنفة بعمودي النص والمرجع البشري."), tools: ["Text Classification Research Preview", "Workspace"], annotation: bi("Required when reliable labels do not already exist.", "مطلوب عند غياب تصنيفات موثوقة."), outputs: bi("Baseline metrics, predictions, confusion matrix, and error taxonomy.", "مقاييس خط أساس وتنبؤات ومصفوفة التباس وتصنيف أخطاء."), evaluation: bi("Held-out accuracy, confusion matrix, and mismatch analysis.", "دقة الاختبار ومصفوفة الالتباس وتحليل الاختلافات."), beginner: bi("Understand labels, train/test separation, baselines, and human reference.", "افهم الفئات وفصل التدريب والاختبار وخط الأساس والمرجع البشري.") },
  "information-extraction": { name: bi("Information Extraction", "استخراج المعلومات"), problem: bi("Turn entities, relations, and terms into structured data.", "تحويل الكيانات والعلاقات والمصطلحات إلى بيانات منظمة."), questions: bi("Which entities, relations, or terms can be extracted consistently?", "ما الكيانات أو العلاقات أو المصطلحات التي يمكن استخراجها باتساق؟"), data: bi("Arabic texts, a defined schema, and an optional human reference.", "نصوص عربية ومخطط محدد ومرجع بشري اختياري."), tools: ["Information Extraction"], annotation: bi("Recommended for evaluation; required for a defensible benchmark.", "يوصى به للتقييم، ويطلب لبناء معيار يمكن الدفاع عنه."), outputs: bi("An entity/term dataset, evaluation, error taxonomy, or prototype.", "مجموعة كيانات أو مصطلحات وتقييم وتصنيف أخطاء أو نموذج."), evaluation: bi("Precision/recall with a valid reference, plus span and category review.", "الدقة والاسترجاع مع مرجع صالح ومراجعة النطاق والفئة."), beginner: bi("Define exactly what counts as an entity, relation, or term.", "حدد بدقة ما يعد كيانًا أو علاقة أو مصطلحًا.") },
  "nlp-experiments": { name: bi("Language Technology & NLP Experiments", "تقنيات اللغة وتجارب NLP"), problem: bi("Controlled computational experiments and prompt/output comparison.", "التجارب الحاسوبية المضبوطة ومقارنة التعليمات والمخرجات."), questions: bi("How does one controlled change affect an NLP result?", "كيف يؤثر تغيير مضبوط في نتيجة مهمة NLP؟"), data: bi("A fixed task, stable inputs, output criteria, and comparison records.", "مهمة ثابتة ومدخلات مستقرة ومعايير مخرجات وسجل مقارنة."), tools: ["NLP Experiments", "Spreadsheet Explorer", "AI Code Assistant", "Google Colab"], annotation: bi("Depends on the task; define human evaluation criteria first.", "يعتمد على المهمة، ويجب تحديد معايير التقييم البشري أولًا."), outputs: bi("A controlled comparison, reproducible workflow, or experiment prototype.", "مقارنة مضبوطة أو مسار قابل لإعادة الإنتاج أو نموذج تجربة."), evaluation: bi("Fixed test cases, a researcher rubric, consistency, and error records.", "حالات اختبار ثابتة ومحكّمات الباحث والاتساق وسجل الأخطاء."), beginner: bi("Change one variable at a time and define what better means before running.", "غيّر متغيرًا واحدًا وحدد معنى الأفضل قبل التشغيل.") },
};

const project = (id, title, problem, impact, path, tools, data, teamType, annotatorsRequired, annotationNotes, complexity, steps, results, evaluation, possibleOutputs, application, tags) => ({ id, title: bi(...title), problem: bi(...problem), impact: bi(...impact), path, tools, dataRequirements: bi(...data), teamType, annotatorsRequired, annotationNotes: bi(...annotationNotes), complexity, steps: bi(...steps), expectedResults: bi(...results), evaluation: bi(...evaluation), possibleOutputs, applicationPotential: bi(...application), tags });

const BASE_PROJECT_CATALOG = [
  project("arabic-stance-reference", ["Human reference for Arabic stance analysis", "بناء مرجع بشري لتحليل الموقف العربي"], ["AI stance labels need a transparent human reference.", "تحتاج تصنيفات الموقف الآلية إلى مرجع بشري واضح."], ["Reusable evidence for evaluating stance systems and errors.", "أدلة قابلة لإعادة الاستخدام لتقييم أنظمة الموقف وأخطائها."], "discourse-pragmatics", ["Discourse Analysis"], ["Arabic passages, a defined stance target, and documented sampling.", "مقاطع عربية وموضوع موقف محدد وعينة موثقة."], "team", true, ["A researcher plus at least two independent annotators is recommended.", "يوصى بباحث ومرمزين مستقلين على الأقل."], "intermediate", [["Define target and guide", "Sample passages", "Annotate independently", "Review AI suggestions", "Resolve disagreements", "Evaluate errors"], ["حدد الموضوع والدليل", "اسحب عينة", "رمز بصورة مستقلة", "راجع المقترحات الآلية", "احسم الخلافات", "قيم الأخطاء"]], ["Human reference, reviewed outputs, disagreements, and error taxonomy.", "مرجع بشري ومخرجات مراجعة وخلافات وتصنيف أخطاء."], ["Annotator agreement, reference comparison, and qualitative error analysis.", "اتفاق المرمزين والمقارنة بالمرجع والتحليل النوعي للأخطاء."], ["paper", "dataset", "benchmark"], ["A reviewed stance-analysis prototype.", "نموذج مراجع لتحليل الموقف."], ["annotation", "evaluation", "team"]),
  project("arabic-terminology", ["Arabic domain terminology extraction assistant", "مساعد استخراج المصطلحات العربية المتخصصة"], ["Domain terminology is difficult to identify consistently.", "يصعب تحديد المصطلحات المتخصصة باتساق."], ["Supports terminology resources and expert review.", "يدعم الموارد المصطلحية ومراجعة الخبراء."], "information-extraction", ["Information Extraction"], ["A rights-cleared domain corpus and terminology criteria.", "مدونة تخصصية مصرح بها ومعايير للمصطلحات."], "team", true, ["Domain experts validate term boundaries and relevance.", "يتحقق خبراء المجال من حدود المصطلحات وصلتها."], "advanced", [["Define criteria", "Prepare texts", "Extract keyphrases", "Review spans", "Build reference", "Analyze errors"], ["حدد المعايير", "جهز النصوص", "استخرج العبارات", "راجع النطاقات", "ابن المرجع", "حلل الأخطاء"]], ["Reviewed terminology dataset and documented errors.", "مجموعة مصطلحات مراجعة وأخطاء موثقة."], ["Precision/recall with a valid reference; otherwise expert review.", "الدقة والاسترجاع مع مرجع صالح، وإلا فمراجعة الخبراء."], ["dataset", "benchmark", "prototype"], ["A terminology search or authoring aid.", "أداة للبحث المصطلحي أو المساعدة في التأليف."], ["extraction", "annotation", "team"]),
  project("arabic-review-classification", ["Arabic reviews: baseline versus AI-assisted classification", "المراجعات العربية: خط الأساس مقابل التصنيف المساند"], ["Classification failures vary across review labels.", "تختلف أخطاء التصنيف بين فئات المراجعات."], ["A transparent comparison beyond one score.", "مقارنة شفافة تتجاوز الدرجة الواحدة."], "text-classification", ["Text Classification Research Preview", "Workspace"], ["Labeled Arabic reviews with documented label definitions.", "مراجعات عربية مصنفة وتعريفات موثقة للفئات."], "individual", false, ["Check existing labels; add annotators if their quality is uncertain.", "افحص الفئات القائمة وأضف مرمزين إذا كانت جودتها غير مؤكدة."], "intermediate", [["Inspect labels", "Prepare split", "Run Naive Bayes", "Run AI sample", "Compare references", "Analyze errors"], ["افحص الفئات", "جهز التقسيم", "شغل Naive Bayes", "شغل عينة AI", "قارن بالمرجع", "حلل الأخطاء"]], ["Baseline metrics, confusion matrix, reviewed predictions, and error taxonomy.", "مقاييس ومصفوفة التباس وتنبؤات مراجعة وتصنيف أخطاء."], ["Held-out accuracy, confusion matrix, category review, and mismatches.", "دقة الاختبار ومصفوفة الالتباس ومراجعة الفئات والاختلافات."], ["paper", "benchmark"], ["A later domain classifier prototype.", "نموذج أولي لاحق لمصنف تخصصي."], ["classification", "evaluation", "individual"]),
  project("specialized-corpus", ["Build a specialized Arabic corpus", "بناء مدونة عربية متخصصة"], ["A domain lacks a documented analysis-ready corpus.", "يفتقر مجال إلى مدونة موثقة وجاهزة للتحليل."], ["Durable research infrastructure and transparent sampling.", "بنية بحثية مستدامة وعينة شفافة."], "corpus-linguistics", ["Corpus Research", "Frequency", "Concordance / Contexts", "N-grams"], ["Rights-cleared texts, metadata, and inclusion/exclusion criteria.", "نصوص مصرح بها وبيانات وصفية ومعايير إدراج واستبعاد."], "team", false, ["Coders may review metadata; linguistic annotation is optional.", "قد يراجع مساهمون البيانات الوصفية، والترميز اللغوي اختياري."], "intermediate", [["Define scope and rights", "Set metadata", "Collect and deduplicate", "Inspect readiness", "Run analyses", "Document limits"], ["حدد النطاق والحقوق", "ضع البيانات الوصفية", "اجمع وأزل التكرار", "افحص الجاهزية", "نفذ التحليل", "وثق القيود"]], ["Documented corpus, metadata inventory, analyses, and limitations.", "مدونة موثقة وجرد وصفي وتحليلات وقيود."], ["Coverage, completeness, duplicate checks, and reproducibility.", "التغطية والاكتمال وفحص التكرار وقابلية إعادة الإنتاج."], ["corpus", "dataset", "paper"], ["A search, teaching, or domain-analysis tool.", "أداة للبحث أو التعليم أو التحليل التخصصي."], ["corpus", "team", "no-annotation"]),
  project("semantic-grouping", ["Human-reviewed semantic grouping of Arabic texts", "التجميع الدلالي المراجع للنصوص العربية"], ["Meaning-based groups may be unstable or opaque.", "قد تكون المجموعات الدلالية غير مستقرة أو غامضة."], ["Documents group boundaries and ambiguous cases.", "يوثق حدود المجموعات والحالات الملتبسة."], "semantics", ["Semantics Research Preview"], ["Short comparable Arabic texts and a defined grouping purpose.", "نصوص عربية قصيرة وهدف محدد للتجميع."], "individual", false, ["A second reviewer strengthens subjective conclusions.", "يقوي المراجع الثاني الاستنتاجات الاجتهادية."], "beginner", [["Define purpose", "Prepare texts", "Generate groups", "Review assignments", "Record ambiguity", "Interpret patterns"], ["حدد الهدف", "جهز النصوص", "ولد المجموعات", "راجع الإسناد", "سجل الغموض", "فسر الأنماط"]], ["Reviewed semantic groups, rationales, and ambiguity log.", "مجموعات دلالية مراجعة ومسوغات وسجل غموض."], ["Researcher review, optional agreement, and disputed-case analysis.", "مراجعة الباحث واتفاق اختياري وتحليل الحالات المختلف عليها."], ["paper", "dataset"], ["A thematic browsing prototype.", "نموذج أولي للتصفح الموضوعي."], ["semantics", "individual", "no-annotation"]),
  project("morphological-ambiguity", ["Morphological ambiguity in Arabic context", "الغموض الصرفي في السياق العربي"], ["One written form may support different contextual analyses.", "قد تقبل الصيغة الواحدة تحليلات سياقية مختلفة."], ["An explainable taxonomy of ambiguity and errors.", "تصنيف قابل للتفسير للغموض والأخطاء."], "morphology-syntax", ["Morphology & Syntax Research Preview", "POS"], ["Arabic sentences containing selected ambiguous forms.", "جمل عربية تتضمن صيغًا مختارة قابلة للغموض."], "team", true, ["Independent linguistic annotation and adjudication are recommended.", "يوصى بترميز لغوي مستقل وتحكيم الخلافات."], "advanced", [["Define ambiguity", "Select cases", "Annotate independently", "Run analysis", "Compare reference", "Classify errors"], ["حدد الغموض", "اختر الحالات", "رمز مستقلًا", "شغل التحليل", "قارن بالمرجع", "صنف الأخطاء"]], ["Reviewed cases, reference annotations, and error taxonomy.", "حالات مراجعة وترميزات مرجعية وتصنيف أخطاء."], ["Agreement, applicable category accuracy, and adjudicated errors.", "الاتفاق ودقة الفئات المناسبة والأخطاء المحكّمة."], ["paper", "dataset", "benchmark"], ["A later disambiguation resource.", "مورد لاحق لإزالة الغموض."], ["morphology", "annotation", "team"]),
  project("prompt-sensitivity", ["Prompt sensitivity in an Arabic NLP task", "حساسية التعليمات في مهمة NLP عربية"], ["Small instruction changes may produce inconsistent outputs.", "قد تنتج تغييرات التعليمات الصغيرة مخرجات غير متسقة."], ["A controlled record of instruction effects and failures.", "سجل مضبوط لأثر التعليمات وحالات الفشل."], "nlp-experiments", ["NLP Experiments"], ["A fixed Arabic test set, one task, two variants, and a rubric.", "اختبار عربي ثابت ومهمة واحدة وصيغتان ومحكّمات."], "individual", false, ["Additional raters help when output quality is subjective.", "يفيد مقيمون إضافيون عندما تكون الجودة اجتهادية."], "intermediate", [["Fix task and inputs", "Define rubric", "Write A and B", "Run both", "Evaluate", "Analyze errors"], ["ثبت المهمة والمدخلات", "حدد المحكّمات", "اكتب أ وب", "شغل الصيغتين", "قيم", "حلل الأخطاء"]], ["Controlled comparison, researcher evaluations, and sensitivity patterns.", "مقارنة مضبوطة وتقييمات الباحث وأنماط الحساسية."], ["Fixed-case rubric, consistency, paired comparison, and error log.", "محكّمات ثابتة واتساق ومقارنة مزدوجة وسجل أخطاء."], ["paper", "benchmark", "prototype"], ["A prompt-testing protocol.", "بروتوكول لاختبار التعليمات."], ["experiment", "evaluation", "individual"]),
  project("speech-act-reference", ["Arabic speech-act annotation study", "دراسة ترميز الأفعال الكلامية العربية"], ["Speech-act boundaries vary by context and judgment.", "تختلف حدود الأفعال الكلامية بحسب السياق والاجتهاد."], ["A reviewed reference for difficult pragmatic cases.", "مرجع مراجع للحالات التداولية الصعبة."], "discourse-pragmatics", ["Pragmatics"], ["Contextual utterances with genre or situation metadata.", "تلفظات سياقية مع بيانات النوع أو الموقف."], "team", true, ["At least two coders and an adjudication guide are recommended.", "يوصى بمرمزين على الأقل ودليل للتحكيم."], "intermediate", [["Define categories", "Write guide", "Sample utterances", "Annotate", "Review AI", "Measure agreement"], ["حدد الفئات", "اكتب الدليل", "اسحب العينة", "رمز", "راجع AI", "قس الاتفاق"]], ["Human reference, agreement record, and pragmatic error cases.", "مرجع بشري وسجل اتفاق وحالات أخطاء تداولية."], ["Inter-annotator agreement and adjudicated analysis.", "اتفاق المرمزين والتحليل بعد التحكيم."], ["paper", "dataset", "benchmark"], ["A pragmatic annotation assistant.", "مساعد للترميز التداولي."], ["pragmatics", "annotation", "team"]),
  project("policy-relations", ["Entity–relation extraction from Arabic policy documents", "استخراج الكيانات والعلاقات من وثائق السياسات"], ["Actors and explicit relations are hard to compare across documents.", "يصعب مقارنة الجهات والعلاقات الصريحة بين الوثائق."], ["Structured evidence with traceable source spans.", "أدلة منظمة ذات نطاقات مصدرية قابلة للتتبع."], "information-extraction", ["Information Extraction"], ["Rights-cleared documents and a narrow extraction schema.", "وثائق مصرح بها ومخطط استخراج ضيق."], "individual", false, ["Expert validation is required before accepting relations as findings.", "يلزم تحقق خبير قبل اعتماد العلاقات نتائج."], "advanced", [["Define schema", "Prepare documents", "Extract entities", "Extract relations", "Review spans", "Classify errors"], ["حدد المخطط", "جهز الوثائق", "استخرج الكيانات", "استخرج العلاقات", "راجع النطاقات", "صنف الأخطاء"]], ["Reviewed entity/relation table with evidence and errors.", "جدول مراجع للكيانات والعلاقات مع الأدلة والأخطاء."], ["Expert review; precision/recall only with a complete reference.", "مراجعة خبير؛ والدقة والاسترجاع مع مرجع مكتمل فقط."], ["paper", "dataset", "prototype"], ["A document exploration prototype.", "نموذج لاستكشاف الوثائق."], ["extraction", "individual", "advanced"]),
  project("comparative-corpus", ["Comparative corpus study of institutional language", "دراسة مدونات مقارنة للغة المؤسسية"], ["Language patterns are often asserted without reproducible evidence.", "توصف الأنماط اللغوية كثيرًا دون أدلة قابلة لإعادة الإنتاج."], ["Connects quantitative patterns to contextual reading.", "يربط الأنماط الكمية بالقراءة السياقية."], "corpus-linguistics", ["Frequency", "Concordance / Contexts", "N-grams"], ["Two comparable rights-cleared corpora with documented sampling.", "مدونتان قابلتان للمقارنة ومصرح بهما مع عينة موثقة."], "individual", false, ["Annotation is unnecessary unless interpretations become coded categories.", "لا يلزم الترميز إلا إذا تحولت التفسيرات إلى فئات."], "beginner", [["Define corpora", "Document sampling", "Process consistently", "Compare counts", "Read contexts", "Report limits"], ["حدد المدونتين", "وثق العينة", "عالج باتساق", "قارن الأعداد", "اقرأ السياقات", "اعرض القيود"]], ["Comparable counts, contextual evidence, and bounded interpretation.", "أعداد قابلة للمقارنة وأدلة سياقية وتفسير منضبط."], ["Reproducibility, justified normalization, and manual context checks.", "قابلية إعادة الإنتاج والمعايرة المبررة وفحص السياقات."], ["paper"], ["A corpus-browsing teaching example.", "مثال تعليمي لتصفح المدونات."], ["corpus", "individual", "beginner", "no-annotation"]),
];

export const PROJECT_CATALOG = Object.freeze([...BASE_PROJECT_CATALOG, ...ARABIC_CHALLENGE_PROJECTS, ...SOCIAL_IMPACT_PROJECTS, ...APPLIED_NEW_PROJECTS]);

export const PROJECT_PATH_ROUTES = {
  "corpus-linguistics": "/research-paths/corpus-linguistics",
  "morphology-syntax": "/ar-tools#morphology-syntax",
  semantics: "/ar-tools#semantics",
  "discourse-pragmatics": "/ar-tools#discourse-pragmatics",
  "text-classification": "/ar-tools#build-tools",
  "information-extraction": "/ar-tools#build-tools",
  "nlp-experiments": "/ar-tools#build-tools",
};

export const PROJECT_TOOL_ROUTES = {
  "Corpus Research": "/tools/corpus-research",
  Frequency: "/tools/frequency",
  "Concordance / Contexts": "/tools/concordance",
  "N-grams": "/tools/ngrams",
  POS: "/tools/pos",
  "Morphology & Syntax Research Preview": "/tools/morphology-syntax",
  "Semantics Research Preview": "/tools/semantics",
  "Discourse Analysis": "/tools/discourse-analysis",
  Pragmatics: "/tools/pragmatics",
  "Text Classification Research Preview": "/tools/text-classification-research",
  Workspace: "/workspace",
  "Information Extraction": "/tools/information-extraction",
  "NLP Experiments": "/tools/nlp-experiments",
  "Spreadsheet Explorer": "/tools/excel",
  "AI Code Assistant": "/tools/code",
  "Google Colab": "/tools/colab",
};

const DATA_DESTINATIONS = {
  "corpus-linguistics": ["Corpus Research", "/tools/corpus-research"],
  "text-classification": ["Workspace", "/workspace"],
  "nlp-experiments": ["Spreadsheet Explorer", "/tools/excel"],
};

export function buildProjectRoadmap(project) {
  const primaryTool = project.tools.find((tool) => PROJECT_TOOL_ROUTES[tool]);
  const primaryRoute = PROJECT_TOOL_ROUTES[primaryTool];
  const dataDestination = DATA_DESTINATIONS[project.path] || ["Workspace", "/workspace"];
  const internal = (stage, label, href, note) => ({ stage, label, href, note, external: false });
  const external = (stage, label, note) => ({ stage, label, href: null, note, external: true });
  const steps = [
    internal("path", PATH_GUIDANCE[project.path].name, PROJECT_PATH_ROUTES[project.path], bi("Open the canonical research path.", "افتح الموطن الأساسي للمسار البحثي.")),
    internal("data", bi(dataDestination[0], dataDestination[0] === "Workspace" ? "مساحة العمل" : dataDestination[0] === "Corpus Research" ? "إنشاء وتحليل المدونة" : "مستكشف الجداول"), dataDestination[1], bi("Prepare and inspect the data supported by LinguaLab.", "جهز البيانات وافحص ما تدعمه LinguaLab.")),
  ];
  if (project.annotatorsRequired) steps.push(external("annotation", bi("Manual annotation and adjudication", "الترميز اليدوي وتحكيم الخلافات"), project.annotationNotes));
  steps.push(
    internal("tool", bi(primaryTool, primaryTool), primaryRoute, bi("Open the exact recommended tool.", "افتح الأداة الموصى بها مباشرة.")),
    internal("run", bi("Run the configured analysis", "شغّل التحليل بعد إعداده"), primaryRoute, bi("Execution remains explicit; no project plan starts a run automatically.", "يبقى التشغيل صريحًا، ولا تبدأ خطة المشروع تحليلًا تلقائيًا.")),
    internal("review", bi("Researcher review", "مراجعة الباحث"), primaryRoute, bi("Review evidence and retain the human decision where the tool supports it.", "راجع الأدلة وسجل القرار البشري عندما تدعم الأداة ذلك.")),
    internal("evaluate", bi("Evaluation", "التقييم"), primaryRoute, bi("Use available reference comparisons and measured outputs only.", "استخدم المقارنات المرجعية والنتائج المقاسة المتاحة فقط.")),
    internal("errors", bi("Error analysis", "تحليل الأخطاء"), primaryRoute, bi("Inspect mismatches or disputed cases supported by the current tool.", "افحص حالات الاختلاف أو الحالات المختلف عليها التي تدعمها الأداة.")),
    internal("interpret", bi("Research Interpreter", "مفسر النتائج البحثية"), "/tools/analyze", bi("Continue to interpretation after obtaining actual results.", "انتقل إلى التفسير بعد الحصول على نتائج فعلية.")),
    internal("report", bi("Research Report", "التقرير البحثي"), "/research-report", bi("Generate or open a report only after a result context exists.", "أنشئ التقرير أو افتحه بعد توفر سياق نتائج فعلي.")),
    internal("writing", bi("Writing support", "دعم الكتابة البحثية"), "/tools/prompt", bi("Prepare a reviewed writing instruction from accepted findings.", "جهز تعليمات كتابة مراجعة انطلاقًا من النتائج المعتمدة.")),
  );
  steps.push(external("responsibility", bi("Research governance", "الحوكمة البحثية"), bi("Data collection, data rights, ethics approval, and specialized statistics remain external when required.", "يبقى جمع البيانات وحقوقها والموافقة الأخلاقية والتحليل الإحصائي المتخصص خطوات خارجية عند الحاجة.")));
  return steps;
}

export function recommendProjects(answers = {}, limit = 4) {
  return PROJECT_CATALOG.map((project) => { const applied = APPLIED_PROJECT_BY_PROJECT_ID[project.id]; return { project, score: (answers.path === project.path ? 5 : 0) + (answers.challenge === project.challengeId || project.challengeIds?.includes(answers.challenge) ? 6 : 0) + (project.possibleOutputs.includes(answers.goal) ? 3 : 0) + (answers.complexity === project.complexity ? 2 : 0) + (answers.team === project.teamType ? 1 : 0) + (answers.annotation && ((answers.annotation === "yes") === project.annotatorsRequired) ? 2 : 0) + (project.tags.includes(answers.task) ? 3 : 0) + (project.tags.includes(answers.challengeFocus) ? 4 : 0) + (answers.socialDomain === project.socialImpact?.domain ? 8 : 0) + (project.tags.includes(answers.socialNeed) ? 5 : 0) + (answers.appliedSector === applied?.sector ? 8 : 0) + (applied?.tags.includes(answers.appliedNeed) ? 5 : 0) }; }).sort((a, b) => b.score - a.score || a.project.id.localeCompare(b.project.id)).slice(0, limit).map(({ project: item }) => item);
}
