export const RESEARCH_PATHS = [
  {
    id: "corpus-linguistics",
    name: { en: "Corpus Linguistics", ar: "لسانيات المدونات" },
    overview: { en: "Study recurring forms and usage patterns across a collection of texts.", ar: "يدرس الأنماط المتكررة واستعمال اللغة في مجموعة من النصوص." },
    question: { en: "Which words, expressions, and sequences characterize this corpus?", ar: "ما الكلمات والتعبيرات والمتتاليات التي تميّز هذه المدونة؟" },
    data: { en: "A text or a collection of texts suitable for comparison and pattern counting.", ar: "نص أو مجموعة نصوص صالحة للمقارنة ورصد الأنماط." },
    available: [
      { href: "/tools/frequency", en: "Frequency", ar: "تحليل التكرار" },
      { href: "/tools/concordance", en: "Concordance / Contexts", ar: "السياقات" },
      { href: "/tools/ngrams", en: "N-grams", ar: "المتتاليات اللفظية" },
    ],
    coming: { en: ["Collocations", "Keyword Analysis", "Corpus Comparison"], ar: ["المصاحبات اللفظية", "تحليل الكلمات المفتاحية", "مقارنة المدونات"] },
    output: { en: "Frequency tables, contextual examples, and recurring sequences.", ar: "جداول تكرار، وأمثلة سياقية، ومتتاليات متكررة." },
    report: { en: "A corpus-pattern report supported by observed counts and contexts.", ar: "تقرير عن أنماط المدونة يستند إلى التكرارات والسياقات المرصودة." },
    beginner: {
      en: "Use this path when you want to discover what repeatedly appears in a body of text. Example: Which expressions recur in university mission statements?",
      ar: "استخدم هذا المسار لاكتشاف ما يتكرر في مجموعة نصوص. مثال: ما التعبيرات المتكررة في رسائل الجامعات؟",
    },
    advanced: { en: "Frequency normalization, concordance interpretation, phrase patterns, and comparative corpus design.", ar: "معايرة التكرار، وتفسير السياقات، وأنماط العبارات، وتصميم المقارنة بين المدونات." },
  },
  {
    id: "text-classification",
    name: { en: "Text Classification", ar: "تصنيف النصوص" },
    overview: { en: "Assign existing labels to texts and evaluate how well a transparent baseline performs.", ar: "يسند تصنيفات موجودة إلى النصوص ويقيّم أداء خط أساس واضح." },
    question: { en: "Can the available text distinguish the predefined categories?", ar: "هل يستطيع النص المتاح التمييز بين الفئات المحددة مسبقًا؟" },
    data: { en: "A labeled dataset with a text column and enough examples in each class.", ar: "مجموعة بيانات مصنفة تضم عمودًا للنص وأمثلة كافية في كل فئة." },
    available: [
      { href: "/workspace", en: "Guided classification workflow · Naive Bayes baseline and evaluation", ar: "مسار تصنيف موجّه · خط أساس Naive Bayes وتقييم الأداء" },
    ],
    coming: { en: ["Dedicated Sentiment Analysis", "Logistic Regression", "SVM comparison"], ar: ["أداة مستقلة لتحليل المشاعر", "الانحدار اللوجستي", "مقارنة آلة المتجهات الداعمة (SVM)"] },
    output: { en: "A baseline score, train/test counts, vocabulary size, and confusion matrix.", ar: "درجة خط أساس، وأعداد التدريب والاختبار، وحجم المفردات، ومصفوفة الالتباس." },
    report: { en: "A classification baseline report with evidence, limitations, and next steps.", ar: "تقرير لخط أساس التصنيف يتضمن الأدلة والقيود والخطوات التالية." },
    beginner: {
      en: "Use this path when texts already have categories you want to predict. Example: Can labeled reviews be classified by sentiment?",
      ar: "استخدم هذا المسار عندما تحمل النصوص فئات تريد التنبؤ بها. مثال: هل يمكن تصنيف المراجعات الموسومة بحسب المشاعر؟",
    },
    advanced: { en: "Transparent Naive Bayes baseline, stratified train/test evaluation, class balance, and error interpretation.", ar: "خط أساس شفاف باستخدام Naive Bayes، وتقسيم طبقي للتدريب والاختبار، وتوازن الفئات، وتفسير الأخطاء." },
  },
  {
    id: "morphology-syntax",
    name: { en: "Morphology & Syntax", ar: "الصرف والنحو" },
    overview: { en: "Examine grammatical categories and structural patterns in text.", ar: "يفحص الفئات النحوية والأنماط البنيوية في النص." },
    question: { en: "Which grammatical categories are prominent in the selected text?", ar: "ما الفئات النحوية البارزة في النص المحدد؟" },
    data: { en: "Text suitable for part-of-speech inspection.", ar: "نص صالح لفحص أقسام الكلام." },
    available: [{ href: "/tools/pos", en: "Parts of Speech Analysis (POS)", ar: "تحليل أقسام الكلام (POS)" }],
    coming: { en: ["Lemmatization", "Morphological Analysis", "Parsing"], ar: ["الإرجاع إلى الصيغة المعجمية", "التحليل الصرفي", "التحليل النحوي الآلي"] },
    output: { en: "An initial view of part-of-speech patterns.", ar: "عرض أولي لأنماط أقسام الكلام." },
    report: { en: "A grammatical-distribution report when analyzable results are available.", ar: "تقرير عن توزيع الفئات النحوية عند توفر نتائج قابلة للتحليل." },
    beginner: {
      en: "Use this path to ask how words function grammatically. Example: Which parts of speech dominate a news sample?",
      ar: "استخدم هذا المسار لمعرفة الوظائف النحوية للكلمات. مثال: ما أقسام الكلام الغالبة في عينة إخبارية؟",
    },
    advanced: { en: "POS distributions, morphological features, syntactic dependencies, and cross-text structural comparison.", ar: "توزيعات أقسام الكلام، والسمات الصرفية، والعلاقات النحوية، والمقارنة البنيوية بين النصوص." },
  },
  {
    id: "semantics",
    name: { en: "Semantics", ar: "الدلالة" },
    overview: { en: "Investigate meaning, conceptual relationships, and semantic variation in language data.", ar: "يبحث في المعنى والعلاقات المفهومية والتنوع الدلالي في البيانات اللغوية." },
    question: { en: "How are meanings and concepts related across the selected texts?", ar: "كيف ترتبط المعاني والمفاهيم عبر النصوص المحددة؟" },
    data: { en: "Texts selected for a clearly defined meaning-focused comparison.", ar: "نصوص مختارة لمقارنة محددة تركز على المعنى." },
    available: [],
    coming: { en: ["Semantic Similarity", "Embeddings", "Topic Modeling", "Clustering"], ar: ["التشابه الدلالي", "التضمينات (Embeddings)", "نمذجة الموضوعات", "التجميع"] },
    output: { en: "Meaning relationships or semantic groupings derived from supported analysis.", ar: "علاقات دلالية أو مجموعات معنوية مستمدة من تحليل مدعوم." },
    report: { en: "A semantic-pattern report once dedicated analysis is available.", ar: "تقرير عن الأنماط الدلالية عند توفر تحليل متخصص." },
    beginner: { en: "Use this path when the question is about meaning rather than word counts. Example: Which concepts occur in similar contexts?", ar: "استخدم هذا المسار عندما يتعلق السؤال بالمعنى لا بعدّ الكلمات. مثال: ما المفاهيم التي تظهر في سياقات متشابهة؟" },
    advanced: { en: "Vector representations, semantic similarity, topic models, and clustering validation.", ar: "التمثيلات المتجهية، والتشابه الدلالي، ونماذج الموضوعات، والتحقق من التجميع." },
  },
  {
    id: "discourse-pragmatics",
    name: { en: "Discourse & Pragmatics", ar: "الخطاب والتداولية" },
    overview: { en: "Study how meaning, stance, and organization emerge beyond individual words and sentences.", ar: "يدرس تشكل المعنى والموقف والتنظيم فيما يتجاوز الكلمات والجمل المفردة." },
    question: { en: "How does a text frame positions and organize meaning for its audience?", ar: "كيف يصوغ النص المواقف وينظم المعنى لجمهوره؟" },
    data: { en: "Complete texts with relevant genre, speaker, or situational context.", ar: "نصوص كاملة مع سياق مناسب للنوع أو المتحدث أو الموقف." },
    available: [],
    coming: { en: ["Discourse Patterns", "Stance", "Framing", "Cohesion / Coherence indicators"], ar: ["أنماط الخطاب", "الموقف", "التأطير", "مؤشرات السبك والانسجام"] },
    output: { en: "Evidence-based discourse observations tied to the source texts.", ar: "ملاحظات خطابية قائمة على أدلة مرتبطة بالنصوص الأصلية." },
    report: { en: "A discourse interpretation report when dedicated evidence is available.", ar: "تقرير لتفسير الخطاب عند توفر أدلة تحليلية متخصصة." },
    beginner: { en: "Use this path to study how language works in context. Example: How do editorials frame responsibility?", ar: "استخدم هذا المسار لدراسة عمل اللغة في السياق. مثال: كيف تؤطر المقالات الافتتاحية مفهوم المسؤولية؟" },
    advanced: { en: "Stance, framing, discourse relations, cohesion, coherence, and context-sensitive interpretation.", ar: "الموقف، والتأطير، والعلاقات الخطابية، والسبك، والانسجام، والتفسير المرتبط بالسياق." },
  },
  {
    id: "information-extraction",
    name: { en: "Information Extraction", ar: "استخراج المعلومات" },
    overview: { en: "Convert selected facts and entities in text into structured research data.", ar: "يحوّل الحقائق والكيانات المحددة في النص إلى بيانات بحثية منظمة." },
    question: { en: "Which named items or key facts can be identified consistently in the texts?", ar: "ما العناصر المسماة أو الحقائق الأساسية التي يمكن تحديدها باتساق في النصوص؟" },
    data: { en: "Texts plus a clear definition of the entities, terms, or facts to extract.", ar: "نصوص مع تعريف واضح للكيانات أو المصطلحات أو الحقائق المطلوب استخراجها." },
    available: [],
    coming: { en: ["Named Entity Recognition", "Terminology Extraction", "Keyword / Keyphrase Extraction"], ar: ["التعرف على الكيانات المسماة", "استخراج المصطلحات", "استخراج الكلمات والعبارات المفتاحية"] },
    output: { en: "Structured entities, terms, or key facts grounded in the source text.", ar: "كيانات أو مصطلحات أو حقائق أساسية منظمة ومستندة إلى النص المصدر." },
    report: { en: "An extraction report once dedicated extraction tools are available.", ar: "تقرير استخراج عند توفر أدوات متخصصة." },
    beginner: { en: "Use this path when you need text converted into a structured list. Example: Which organizations are named in policy documents?", ar: "استخدم هذا المسار عندما تحتاج إلى تحويل النص إلى قائمة منظمة. مثال: ما الجهات المذكورة في وثائق السياسات؟" },
    advanced: { en: "Entity schemas, terminology boundaries, extraction precision and recall, and annotation agreement.", ar: "مخططات الكيانات، وحدود المصطلحات، ودقة الاستخراج واسترجاعه، واتفاق الترميز." },
  },
  {
    id: "language-technology",
    name: { en: "Language Technology & NLP Experiments", ar: "تقنيات اللغة وتجارب NLP" },
    overview: { en: "Prepare data and build reproducible computational experiments for language research.", ar: "يهيئ البيانات ويبني تجارب حاسوبية قابلة لإعادة الإنتاج في البحث اللغوي." },
    question: { en: "How can this research task be prepared, implemented, reviewed, and reproduced computationally?", ar: "كيف يمكن إعداد هذه المهمة البحثية وتنفيذها ومراجعتها وإعادة إنتاجها حاسوبيًا؟" },
    data: { en: "A research task, structural spreadsheet metadata, or reviewed code appropriate to the current step.", ar: "مهمة بحثية، أو بيانات وصفية بنيوية لجدول، أو شفرة مراجعة تناسب الخطوة الحالية." },
    available: [
      { href: "/tools/prompt", en: "Prompt Assistant", ar: "مساعد التعليمات" },
      { href: "/tools/excel", en: "Spreadsheet Explorer", ar: "مستكشف الجداول" },
      { href: "/tools/code", en: "AI Code Assistant", ar: "مساعد البرمجة بالذكاء الاصطناعي" },
      { href: "/tools/colab", en: "Google Colab", ar: "Google Colab" },
    ],
    coming: { en: ["Experiment tracking", "Model comparison workspace"], ar: ["تتبّع التجارب", "مساحة مقارنة النماذج"] },
    output: { en: "An editable task, structural data profile, reviewed code response, or reproducible notebook step.", ar: "مهمة قابلة للتحرير، أو ملف بنيوي للبيانات، أو استجابة برمجية مراجعة، أو خطوة قابلة لإعادة الإنتاج في دفتر حاسوبي." },
    report: { en: "A reproducibility-oriented workflow record; research reports remain tied to completed analysis results.", ar: "سجل لمسار عمل يركز على قابلية إعادة الإنتاج؛ وتبقى التقارير البحثية مرتبطة بنتائج التحليل المكتملة." },
    beginner: { en: "Use this path when you need help moving from data preparation to code and a runnable notebook. Example: How can I prepare and reproduce a text-classification experiment?", ar: "استخدم هذا المسار للانتقال من إعداد البيانات إلى الشفرة ودفتر قابل للتشغيل. مثال: كيف أهيئ تجربة لتصنيف النصوص وأعيد إنتاجها؟" },
    advanced: { en: "Prompt specification, data-shape inspection, code review, reproducible notebooks, and evaluation workflow design.", ar: "تحديد التعليمات، وفحص بنية البيانات، ومراجعة الشفرة، والدفاتر القابلة لإعادة الإنتاج، وتصميم مسار التقييم." },
  },
];
